apiVersion: v1
kind: Service
metadata:
  name: uda-app-service
spec:
  type: NodePort
  selector:
    pod: uda-app
  ports:
    - name: uda-app-port
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-app-deployment
  labels:
    component: uda-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: uda-app
  template:
    metadata:
      labels:
        pod: uda-app
    spec:
      containers:
      - name: uda-app
        image: thienphuoc1990/udacity-devops-capstone-app
        imagePullPolicy: Always  
        ports:
        - containerPort: 80